project:
  type: website

website:
  title: "The Learning Curve"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anshu-mishra25
      - icon: twitter
        href: https://x.com/AnshuMishr22631
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual

